# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nan Copeland
email: nmcopeland1@gmail.com
description: Nan Copeland is a digital designer at Industry Dive in Washington D.C.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nancopeland.com" # the base hostname & protocol for your site 

# Build settings
markdown: kramdown
